import nodemailer from 'nodemailer';
import { GOVERNMENT_EMAILS } from '../config/governmentEmails.js';

// -------------------------------------------------------------
// 1. Setup Nodemailer Transport (STABILITY FIX)
// -------------------------------------------------------------
const transporter = nodemailer.createTransport({
  host: 'smtp.gmail.com',
  port: 465, // 👈 Using 465 for SSL (More stable on Render)
  secure: true, // 👈 Required for port 465
  auth: {
    user: process.env.SMTP_USER, // sai1234comon@gmail.com
    pass: process.env.SMTP_PASS // ⚠️ Ensure this is a 16-character App Password
  },
  // 🛡️ Reliability settings to prevent "ETIMEDOUT"
  connectionTimeout: 15000, // 15 seconds
  greetingTimeout: 15000,
  socketTimeout: 20000,
});

const escapeHtml = (unsafe) => {
  return unsafe
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
};

// =========================================================================================
// ✅ FUNCTION A: Send Issue Report to Authority
// =========================================================================================
export const sendEmailToAuthority = async (issue) => {
  try {
    const authorityEmail = GOVERNMENT_EMAILS[issue.category];

    if (!authorityEmail) {
      console.error(`No authority email found for category: ${issue.category}`);
      return false;
    }

    const mailOptions = {
      from: `"Resolveit Official Report" <${process.env.SMTP_USER}>`,
      to: authorityEmail,
      subject: `Community Issue Report: ${escapeHtml(issue.title)}`,
      html: `
        <div style="font-family: sans-serif; line-height: 1.6;">
          <h2>Official Community Issue Report</h2>
          <p><strong>Category:</strong> ${issue.category}</p>
          <p><strong>Title:</strong> ${issue.title}</p>
          <p><strong>Description:</strong> ${issue.description}</p>
          <p>This report was generated by the Resolveit Community Platform.</p>
        </div>
      `,
    };

    await transporter.sendMail(mailOptions);
    console.log(`Authority Email sent successfully to ${authorityEmail}`);
    return true;
  } catch (error) {
    console.error('Failed to send authority email:', error);
    throw error;
  }
};

// =========================================================================================
// ✅ FUNCTION B: Send Feedback Notification to Admin
// =========================================================================================
export const sendFeedbackNotification = async (feedbackData, userEmail) => {
  try {
    const recipientEmail = "lyfspot@zohomail.in";

    const mailOptions = {
      from: `"Resolveit Feedback" <${process.env.SMTP_USER}>`,
      to: recipientEmail,
      replyTo: userEmail, // 🟢 Admin replies go directly to the user
      subject: `[FEEDBACK - ${feedbackData.type}] ${feedbackData.subject}`,
      html: `
        <div style="font-family: sans-serif; padding: 20px; border: 1px solid #eee;">
          <h2>New Feedback Received</h2>
          <p><strong>From User:</strong> ${userEmail}</p>
          <p><strong>Type:</strong> ${feedbackData.type}</p>
          <p><strong>Subject:</strong> ${feedbackData.subject}</p>
          <hr>
          <p><strong>Message:</strong></p>
          <div style="padding: 10px; background-color: #f9f9f9; border-left: 3px solid #007bff;">
            ${escapeHtml(feedbackData.message)}
          </div>
        </div>
      `,
    };

    const info = await transporter.sendMail(mailOptions);
    console.log('Feedback Email sent: %s', info.messageId);
    return true;
  } catch (error) {
    console.error('Error sending feedback email:', error);
    return false;
  }
};