import nodemailer from 'nodemailer';
import { GOVERNMENT_EMAILS } from '../config/governmentEmails.js';

// -------------------------------------------------------------
// 1. Setup Nodemailer Transport (PRODUCTION-SAFE FOR GMAIL)
// -------------------------------------------------------------
const transporter = nodemailer.createTransport({
  host: 'smtp.gmail.com',
  port: 465,
  secure: true,
  auth: {
    user: process.env.SMTP_USER, // your Gmail
    pass: process.env.SMTP_PASS // 16-digit App Password
  },

  // 🛡️ Stability (VERY IMPORTANT)
  pool: true,
  maxConnections: 1,
  maxMessages: 5,
  connectionTimeout: 15000,
  greetingTimeout: 15000,
  socketTimeout: 20000,
});

// -------------------------------------------------------------
// 2. Helper: Escape HTML
// -------------------------------------------------------------
const escapeHtml = (str = '') =>
  str.replace(/[&<>"']/g, (m) => ({
    '&': '&amp;',
    '<': '&lt;',
    '>': '&gt;',
    '"': '&quot;',
    "'": '&#039;',
  }[m]));

// =========================================================================================
// ✅ FUNCTION A: Send Issue Report to Authority (NON-BLOCKING)
// =========================================================================================
export const sendEmailToAuthority = (issue) => {
  const authorityEmail = GOVERNMENT_EMAILS[issue.category];

  if (!authorityEmail) {
    console.error(`No authority email found for category: ${issue.category}`);
    return;
  }

  const mailOptions = {
    from: `"Resolveit Official Report" <${process.env.SMTP_USER}>`,
    to: authorityEmail,
    subject: `Community Issue Report: ${escapeHtml(issue.title)}`,
    html: `
      <div style="font-family: sans-serif; line-height: 1.6;">
        <h2>Official Community Issue Report</h2>
        <p><strong>Category:</strong> ${escapeHtml(issue.category)}</p>
        <p><strong>Title:</strong> ${escapeHtml(issue.title)}</p>
        <p><strong>Description:</strong> ${escapeHtml(issue.description)}</p>
        <p>This report was generated by the Resolveit Community Platform.</p>
      </div>
    `,
  };

  // 🔥 DO NOT await (fire-and-forget)
  transporter.sendMail(mailOptions)
    .then(() => {
      console.log(`Authority Email sent to ${authorityEmail}`);
    })
    .catch((error) => {
      console.error('Authority email failed:', error.message);
    });
};

// =========================================================================================
// ✅ FUNCTION B: Send Feedback Notification to Admin (NON-BLOCKING)
// =========================================================================================
export const sendFeedbackNotification = (feedbackData, userEmail) => {
  const recipientEmail = 'lyfspot@zohomail.in';

  const mailOptions = {
    from: `"Resolveit Feedback" <${process.env.SMTP_USER}>`,
    to: recipientEmail,
    replyTo: userEmail,
    subject: `[FEEDBACK - ${escapeHtml(feedbackData.type)}] ${escapeHtml(feedbackData.subject)}`,
    html: `
      <div style="font-family: sans-serif; padding: 20px; border: 1px solid #eee;">
        <h2>New Feedback Received</h2>
        <p><strong>From User:</strong> ${escapeHtml(userEmail)}</p>
        <p><strong>Type:</strong> ${escapeHtml(feedbackData.type)}</p>
        <p><strong>Subject:</strong> ${escapeHtml(feedbackData.subject)}</p>
        <hr>
        <p><strong>Message:</strong></p>
        <div style="padding: 10px; background-color: #f9f9f9; border-left: 3px solid #007bff;">
          ${escapeHtml(feedbackData.message)}
        </div>
      </div>
    `,
  };

  // 🔥 DO NOT await (fire-and-forget)
  transporter.sendMail(mailOptions)
    .then((info) => {
      console.log('Feedback Email sent:', info.messageId);
    })
    .catch((error) => {
      console.error('Feedback email failed:', error.message);
    });
};

// =========================================================================================
// ✅ FUNCTION C: Send Password Reset Email (NON-BLOCKING)
// =========================================================================================
export const sendResetPasswordEmail = (userEmail, resetToken) => {
  const resetUrl = `https://resolveit-community.vercel.app/reset-password/${resetToken}`;

  const mailOptions = {
    from: `"Resolveit Support" <${process.env.SMTP_USER}>`,
    to: userEmail,
    subject: 'Reset Your Resolveit Password',
    html: `
      <div style="font-family: sans-serif; padding: 20px;">
        <h2>Password Reset Request</h2>
        <p>You requested to reset your password. Click the button below to proceed:</p>
        <a href="${resetUrl}" style="background-color: #2563eb; color: white; padding: 10px 20px; text-decoration: none; border-radius: 5px; display: inline-block; margin: 20px 0;">
          Reset Password
        </a>
        <p>If you didn't request this, please ignore this email.</p>
        <p>Link expires in 1 hour.</p>
      </div>
    `,
  };

  // 🔥 NON-BLOCKING: Fire and forget
  transporter.sendMail(mailOptions)
    .then(() => console.log(`Reset email sent to ${userEmail}`))
    .catch((err) => console.error('Reset email failed:', err.message));
};